version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 5
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 5
      runas: root