services:
  api:
    build: ./backend       
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/backend
    command: bash -c "python3 APIs.py run server 0.0.0.0:5001"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend